### PR TITLE
Swift3 migration

### PR DESCRIPTION
**Pull request by DiogoAndre**
Anyone ready for Swift 3? 😄 

Ok, this is probably - as in most likely absolutely - not ready for production 🙈. But it is working! And by working I mean the framework compiles, even macOS demo project complies and you can chat with yourself if you have a Parse server handy.

Maybe solves #63 and #46 

cheers!

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by andrewjedi** [comment]
Thank you so much! Can't wait to test this!

**Comment by flovilmart** [comment]
@DiogoAndre Thanks for paving the way! I'll close that one for now, as all the tooling needs a change to work against xcode8. Follow the continuity on #70.

I'm also adding Carthage support as my future setup will require to be mixed (using old ass pods that don't support frameworks)

**Comment by DiogoAndre** [comment]
No problem @flovilmart ! thanks for getting into this!

**Comment by flovilmart** [comment]
The toolchain is good on my side, still the PFQuery extension that would need to be written in obj-c to make sense in Swift :/

**Pull request closed without merging**
