### PR TITLE
Updating Changelog for release 2.6.1

### PR DESCRIPTION
**Pull request by noobs2ninjas**

### CODE REVIEW

**Review by TomWFox — CHANGES_REQUESTED** [review]
In the Podspec you have bumped the version to 2.7.0?

**Comment by noobs2ninjas** [comment]
Good catch.

**Review by TomWFox — APPROVED** [review]

**Comment by TomWFox** [comment]
Build failed :(

**Comment by noobs2ninjas** [comment]
Yea I saw that. I dont know how thats possible when it passed here.

**Comment by noobs2ninjas** [comment]
What we logs I saw in last build that I dont see in this one. 

```
  - WARN  | [OSX] xcodebuild:  Parse/Parse/Parse/Internal/PFDevice.m:109:49: warning: 'operatingSystemVersion' is only available on macOS 10.10 or newer [-Wunguarded-availability]
822    - NOTE  | [OSX] xcodebuild:  /Applications/Xcode-10.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSProcessInfo.h:54:47: note: 'operatingSystemVersion' has been explicitly marked partial here
823    - NOTE  | [OSX] xcodebuild:  Parse/Parse/Parse/Internal/PFDevice.m:109:49: note: enclose 'operatingSystemVersion' in an @available check to silence this warning
```

Which means we crashed before or during this.

**Comment by noobs2ninjas** [comment]
Think I should just put the dependency back to 1.17.0?

**Comment by TomWFox** [comment]
Up to you.

**Pull request merged**
