### PR TITLE
Use wss schema if api uses https

### PR DESCRIPTION
**Pull request by vstepanyuk**

### CODE REVIEW

**Comment by nlutsenko** [comment]
Looks good, minus whitespace changes - please remove them and we are going to merge this.

**Comment by vstepanyuk** [comment]
ok, will do

**Comment by vstepanyuk** [comment]
Done

**Comment by nlutsenko** [comment]
That point above from bot about CLA looks valid. 
Can you please sin and accept the CLA? Unfortunately, we won't be able to merge it without it.

**Comment by vstepanyuk** [comment]
Can you explain me, what should I do. I didn't get, sorry)

**Comment by vstepanyuk** [comment]
Sorry, got it now) didn't see comment. I signed it

**Pull request merged**
