### PR TITLE
Updating Dependencies

### PR DESCRIPTION
**Pull request by noobs2ninjas**
- Updating starscream to 3.1.1 for Swift 5 compatibility
- Parse 1.18.0 which includes Bolts 1.9.1 that adds catalyst compatibility and fixes App Store UIWebView deprication requirements.

### CODE REVIEW

**Comment by noobs2ninjas** [comment]
@drdaz is this all you think we need other than obviously the changelog being updated?

Starscream 4.0+ requires a lot more fixes because they updated their Websocket Delegate as well as some of their initializer functions. So for now I'm just going to leave it at 3.1.1 which includes Swift 5 compatibility. Figured thats fine unless you see a need to go to the absolute latest version.

**Comment by noobs2ninjas** [comment]
Looks like everything is building! This will be ready to be released once merged.

**Comment by TomWFox** [comment]
Before you publish the release I will need to generate a new cocoa pods token.

Edit: done, I reused the token from the main sdk - I'm assuming that will work.

**Comment by noobs2ninjas** [comment]
Need a approval. ParseLiveQuery will deploy automatically once I finalize the release. Have to merge this first though.

**Review by drdaz — APPROVED** [review]
Looks fine to me.

**Review by TomWFox — APPROVED** [review]

**Comment by TomWFox** [comment]
Cocoapod is out, api ref failed

**Comment by TomWFox** [comment]
Weird error

**Pull request merged**
