### PR TITLE
Switch CI to main branch

### PR DESCRIPTION
**Pull request by cbaker6**
Hey @TomWFox, can you switch the default branch and the branch protections before approving this PR?

### CODE REVIEW

**Comment by TomWFox** [comment]
We had discussed waiting to change more popular repos until GitHub allows a 'seamless transition' to alleviate any issues with clones etc. I would say this repo comes into that bracket?

**Comment by cbaker6** [comment]
We can wait on this one. I did it on here because it doesn’t seem like many changes, issues, and PRs occur on this repo. It does have a decent number for stars and forks

**Comment by TomWFox** [comment]
Yeah, there isn't much activity. My main concern is causing issues with people trying to contribute (it may be largely a non issue).

From the [GitHub guidance](https://github.com/github/renaming) it says...
> we’re also looking into redirecting users who git fetch or git clone the old branch name to the new branch name (with a warning and instructions to update their local clone), so it’s easy for your contributors to move

I'm guessing if you did `git fetch` or `git clone` on the old branch name it would just say that it failed because the branch doesn't exist and then it would break pretty easy for someone to check the repo and see the new main branch. But I don't know if that is that case which is why I'm hesitant.

**Comment by cbaker6** [comment]
> I'm guessing if you did git fetch or git clone on the old branch name it would just say that it failed because the branch doesn't exist and then it would break pretty easy for someone to check the repo and see the new main branch. But I don't know if that is that case which is why I'm hesitant.

In these cases, the user would still be okay because if they ran `git fetch` on the remote it fetches updates for all branches, giving them the `main` branch. If they still have `master` locally they can still create a PR from there into upstream `main`. If they are doing `git clone` the link from GitHub would point to `main`

**Comment by TomWFox** [comment]
I guess though that assumes they know that the repo has switched the default branch to main - hence this comment from GitHub...
> (with a warning and instructions to update their local clone), so it’s easy for your contributors to move

**Comment by cbaker6** [comment]
I figured if a contributor plans to make an update they would first attempt to get the latest up-to-date code by fetching/pulling. At that time if they are fetching/pulling the master branch, there wouldn’t be anything there and I assume they will get an error. My guess is they will then go to the github repo page and the “main” branch will be the default. Even if they submit a PR from their old “master” branch, it would default to the new “main” branch.

**Comment by TomWFox** [comment]
I've switched it, the risk to contribution does seem very low.

**Review by TomWFox — APPROVED** [review]

**Pull request merged**
