### PR TITLE
Replacing with new version of trySetError and trySetResult

### PR DESCRIPTION
**Pull request by jorourke**
Believe this needs to be changed using the latest Bolts-Swift.

### CODE REVIEW

**Comment by ghost** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by ghost** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by p4checo** [comment]
I only saw this PR after submitting my own, sorry 😅 

We are solving the same issue, I believe. Please take a look at my PR (#51) and tell me what you think.

Cheers 🍻

**Comment by jorourke** [comment]
Thanks for integrating

**Pull request closed without merging**
