### PR TITLE
Remove Bolts dependency and related helper files

### PR DESCRIPTION
**Pull request by JoeSzymanski**
Based on discussions in https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/222 around how to handle the Bolts dependency, it was determined the best course of action is probably to remove the Bolts dependency entirely, including the small set of helper code that made use of it.

Since the helper code is not complex and can easily be added by developers to their own projects, it was agreed that the removal of the Bolts dependency outweighed the benefits of having these helper methods available by default.

### CODE REVIEW

**Review by noobs2ninjas — APPROVED** [review]

**Comment by noobs2ninjas** [comment]
Assuming this builds on travis. We are good to go.

**Comment by JoeSzymanski** [comment]
@noobs2ninjas It looks like something just got stuck i nthe one Cocoapods check. Is there a way to retrigger it to try again?

**Comment by SWereszczynski** [comment]
@noobs2ninjas Can you take a look at the Cocoapods step? I will appreciate your help.

**Comment by noobs2ninjas** [comment]
@JoeSzymanski restarted it and it seems like its passed now.

**Comment by JoeSzymanski** [comment]
I think someone can merge this now. I don't appear to have write access to do so.

**Review by ShawnBaek — APPROVED** [review]

**Comment by JoeSzymanski** [comment]
Would it be possible to get a release with this change? We'd like to move forward on the UIWebView removals, but are blocked on this at the moment.

**Comment by noobs2ninjas** [comment]
@JoeSzymanski the guys who manage Bolts are set to release a new release today fixing this exact issue. The moment that is done Parse and ParseLiveQuery will release with many changes and updated dependency versions.

**Pull request merged**
