### PR TITLE
Update Bolt-Swift 1.4.0

### PR DESCRIPTION
**Pull request by ShawnBaek**
I edit Cartfile to support Bolt-Swift 1.4.0 and Carthage update.

Please review my PR and Approve this.

It is working fine on XCode 10, Swift 4.2.

### CODE REVIEW

**Comment by flovilmart** [comment]
Can you update the podspec file as well so all Bolts dependencies are the same?

**Comment by ShawnBaek** [comment]
I edit the PodFile like below:

```Ruby
Pod::Spec.new do |s|
  s.name             = 'ParseLiveQuery'
  s.version          = '2.4.0'
  s.license          =  { :type => 'BSD' }
  s.summary          = 'Allows for subscriptions to queries in conjunction with parse-server.'
  s.homepage         = 'http://parseplatform.org'
  s.social_media_url = 'https://twitter.com/ParsePlatform'
  s.authors          = { 'Parse Community' => 'info@parseplatform.org', 'Richard Ross' => 'richardross@fb.com', 'Nikita Lutsenko' => 'nlutsenko@me.com', 'Florent Vilmart' => 'florent@flovilmart.com' }

  s.source       = { :git => 'https://github.com/ParsePlatform/ParseLiveQuery-iOS-OSX.git', :tag => s.version.to_s }

  s.requires_arc = true

  s.platform = :ios, :osx, :tvos
  s.swift_version = '4.2'
  s.cocoapods_version = '>= 1.4'

  s.ios.deployment_target = '8.0'
  s.tvos.deployment_target = '9.0'
  s.osx.deployment_target = '10.10'


  s.source_files = 'Sources/ParseLiveQuery/**/*.{swift,h}'
  s.module_name = 'ParseLiveQuery'

  s.dependency 'Parse', '~> 1.17.1'
  s.dependency 'Bolts-Swift', '~> 1.4.0'
  s.dependency 'Starscream', '~> 3.0.6'
  s.dependency 'Bolts', '~> 1.9.0'
end
```
And I got an message below after run `sh publish.sh`

```bash
You (shawn@shawnbaek.com) are not allowed to push new versions for this pod. The owners of this pod are nlutsenko@me.com, cocoapods@fb.com, and florent@flovilmart.com.
```

I think a Parse-LiveQuery needs to update latest version of dependencies.

The latest version of dependencies is
- Bolt-Swift 1.4.0
- Bolt 1.9.0
- Starscream 3.0.6
- Parse 1.17.1

Am I right? I want to hear your advice.

Thank you

**Comment by flovilmart** [comment]
Just editing the file is enough, please commit your changes.

Why did you attempt to run publish?

**Comment by ShawnBaek** [comment]
Thanks for advising me.

I will commit `ParseLiveQuery.podspec`

**Comment by flovilmart** [comment]
That didn’t answer the question.

**Comment by ShawnBaek** [comment]
This is my first time to contribute OpenSource Project.

I was thinking run `sh publish.sh` is necessary to reflect the edited podfile.

**Comment by flovilmart** [comment]
It is necessary to publish a new version of the pod which is restricted to maintainers and owners of the project. 

Thanks for your contribution.

**Comment by flovilmart** [comment]
@ShawnBaek it seems that Starscream cannot build because CommonCrypto is not found.

https://circleci.com/gh/parse-community/ParseLiveQuery-iOS-OSX/686

**Comment by ShawnBaek** [comment]
> @ShawnBaek it seems that Starscream cannot build because CommonCrypto is not found.
> 
> https://circleci.com/gh/parse-community/ParseLiveQuery-iOS-OSX/686

Refer to https://github.com/daltoniam/Starscream/issues/575, It seems to have a problem in xcode 9.

How about change the Circle CI build config

defaults: &defaults
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail

----
defaults: &defaults
    macos:
      xcode: **"10.0"**
    shell: /bin/bash --login -eo pipefail

I will check this weekend.

**Comment by flovilmart** [comment]
Thanks for moving forward with this! Why is the deployment target being set to 12? This seems high

**Comment by ShawnBaek** [comment]
-> continuous-integration/travis-ci/pr — The Travis CI build failed

```json
{
  "os": "osx",
  "env": "CocoaPods",
  "cache": [
    "cocoapods"
  ],
  "stage": "distribution",
  "install": "bundle install",
  "language": "objective-c",
  "osx_image": "xcode9"
}
```
Could you change "osx_image": "xcode9" to "osx_image": "xcode10"?

**Comment by ShawnBaek** [comment]
> Thanks for moving forward with this! Why is the deployment target being set to 12? This seems high


CI says: **module file**'s minimum deployment target is ios12 v12. 

It seems that the latest Bolt-Swift is set to v12. 

So I just changed to build pass, but I'm going to take care of more detail this weekend.

**Comment by flovilmart** [comment]
You probably can change the image with this PR as well for Travis :)

Regarding the Bolts-Swift min target being 12, then we should not bump to this one, as many users using live Query won’t be able to use it

**Comment by StarLard** [comment]
Is there a median version of Bolts that can be pointed to then? As it stands the latest release is incompatible with Swift 4.2.

**Comment by flovilmart** [comment]
@ccfriden feel free to ask the Bolts maintainers

**Comment by StarLard** [comment]
@ShawnBaek Where are you seeing that the deployment target is iOS 12? I'm seeing it listed as iOS 8 in the Bolts-Swift podspec and project files.

**Comment by ShawnBaek** [comment]
There are two problems here.

screen shot 2018-11-04 at 1 19 51 am

screen shot 2018-11-04 at 1 24 23 am

And I want to check the travis.yml file.

```yml
branches:
  only:
    - master
    - /^v?[0-9]+\.[0-9]+\.[0-9]+(-.*)?$/
language: objective-c
xcode_workspace: ParseLiveQuery.xcworkspace
xcode_scheme:
	- ParseLiveQuery-iOS
	- ParseLiveQuery-OSX
	- LiveQueryDemo
	- LiveQueryDemo-ObjC
xcode_destination:
	- platform=iOS Simulator, OS=12.1, name=iPhone X
	- platform=macOS
os: osx
osx_image: xcode10.1
cache:
  - cocoapods
install:  bundle install

jobs:
  include:
    - stage: distribution
      env: CocoaPods
      deploy:
        provider: script
        skip_cleanup: true
        script: ./publish.sh
        on:
          tags: true
          all_branches: true
    - stage: distribution
      env: Docs
      script: bundle exec jazzy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        local_dir: docs/
        on:
          all_branches: true

```

**Comment by StriderHND** [comment]
How this ended?

**Comment by ShawnBaek** [comment]
> How this ended?

I'm going to handle it this weekend.

**Comment by ShawnBaek** [comment]
I will close this issue. I'm going to resolve carthage build problem and then open this PR again

**Pull request closed without merging**
