### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by flovilmart**

### CODE REVIEW

**Comment by flovilmart** [comment]
@dstarke I built upon your PR and fixed the issues for the podfile. I however am not really happy to rely on a forked version of SocketRocket for the pods.

**Comment by flovilmart** [comment]
@dstarke I decided to go the extreme way, use Starscream instead of SR. Seems that Starscream is well supported and maintained. What do you think?

**Comment by dstarke** [comment]
@flovilmart That seems like a reasonable choice. I had to patch SocketRocket even further to produce a releasable app.

**Comment by flovilmart** [comment]
Uhm alright. Can you update me if it works / integrates well with Carthage? (and is reasonably stable)

**Comment by dstarke** [comment]
I think it works. I've been able to build it and run successfully via Carthage (I had to modify my project to remove the SocketRocket framework and add the Starscream framework for the copy-frameworks step, so it isn't a drop-in replacement).

Since my project uses a fork which also has the fix-object-decoding branch merged into it, and I have code that doesn't work without that, I have a little more work to do before I can see how reliable it is in an actual product.

**Comment by flovilmart** [comment]
> (I had to modify my project to remove the SocketRocket framework

Yeah that would be expected for a carthage setup, I'll bump the tag to a major so no-one is surprised.

> Since my project uses a fork which also has the fix-object-decoding branch

I merge the fix object decoding to master and rebased that branch as well.

**Comment by dstarke** [comment]
Thanks! I have my manually merged version running now, and it seems to be working.

**Comment by flovilmart** [comment]
SO that's great news then! let me know if there is anything broken there

**Comment by flovilmart** [comment]
@dstarke I just tested with my setup with Cocoapods, I didn't find anything crazy or weird happening. Let's merge that and release.

**Pull request merged**
