### PR TITLE
Release 2.6.0

### PR DESCRIPTION
**Pull request by acinader**

### CODE REVIEW

**Comment by acinader** [comment]
@ananfang or @junya100 
would one of you please take a look at this pull request and let me know if it looks good to make the release?

**Comment by ananfang** [comment]
@acinader Great! Look forward to releasing this version.

**Comment by acinader** [comment]
@ananfang or @junya100 can you confirm that this deployed properly?

**Comment by TomWFox** [comment]
@acinader Annoyingly, it seems I still wasn’t watching this repo so missed this but I just noticed that the 2.6.0 release wasn’t successful. I try and look into it.

**Comment by acinader** [comment]
:( I see the error: 

```
FAILED: tar -Pzcf /Users/travis/.casher/push.tgz 
tar:
no
files
or
directories
specified
```
not sure how to fix.  We really need someone who is used to deploying these kinds of assets.

**Comment by noobs2ninjas** [comment]
Ouch. So travis pushes our updates when we mark a release @TomWFox?

**Comment by noobs2ninjas** [comment]
Who does the Parse iOS release deployment @TomWFox ?

**Comment by TomWFox** [comment]
That's how most of the repos work, but I haven't had a chance to look at this.

**Comment by TomWFox** [comment]
No one - the last release was made by @flovilmart and he is no longer working on the project.

**Comment by noobs2ninjas** [comment]
@TomWFox I got this figured out I think. What I read other repositories do to push and what this specific commit was missing that the other release commits had was a tag. We need to commit called "Release 2.6.0" with the tag "2.6.0" .

**Comment by noobs2ninjas** [comment]
In fact I just verified thats what we need. If we go to a build like [this](https://travis-ci.org/parse-community/ParseLiveQuery-iOS-OSX/jobs/513198771) one thats a commit to master. At the end youll notice it says "Skipping a deployment with the script provider because this is not a tagged commit".

**Comment by noobs2ninjas** [comment]
So actually @TomWFox we could change the commit name and add a tag to it.

**Comment by noobs2ninjas** [comment]
Actually nevermind. Let's commit this one. I want to update build notes and then I'll do one as well as fix some formatting issues and update readme.

**Pull request merged**
