### PR TITLE
Added @objc to compile with objective-c

### PR DESCRIPTION
**Pull request by junya100**
I'm using initWithServer method from objective-c.
But current latest version(2.5.0) can't be compiled because "init" method is not open for objective-c.
I added @objc to some method. Please review it.

Best regards, Junya

### CODE REVIEW

**Review by jpbernius — APPROVED** [review]

**Review by laramarie — APPROVED** [review]

**Comment by flovilmart** [comment]
@acinader @Tom-Fox1 you should probably watch all repositories, people attempt to contribute here...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Review by flovilmart — APPROVED** [review]

**Comment by acinader** [comment]
@flovilmart, thanks.  Will do

**Comment by TomWFox** [comment]
@acinader should we make a new release?

**Comment by relatedcode** [comment]
@jpbernius @TomWFox @acinader @flovilmart @junya100 

Hi everyone,

Is there any chance to have a new release with these changes?

If no, then could you please help me how can I install the latest codebase using CocoaPods?

Thanks! :)

**Comment by flovilmart** [comment]
`how can I install the latest codebase using CocoaPods?`

```
pod "parse-community/ParseLiveQuery-iOS-OSX#master"
```

Should do the trick

**Comment by relatedcode** [comment]
@flovilmart Thank you! :)

**Comment by relatedcode** [comment]
@flovilmart Unfortunately the CocoaPods says:

> [!] Unable to find a specification for `parse-community/ParseLiveQuery-iOS-OSX#master`

**Comment by TomWFox** [comment]
@relatedcode I think something like this should work...
```
pod 'ParseLiveQuery' , :git => 'https://github.com/parse-community/ParseLiveQuery-iOS-OSX', :branch => 'master'
```

**Comment by relatedcode** [comment]
@TomWFox This worked. Thank you! :)

**Comment by acinader** [comment]
@flovilmart thanks!  see: https://github.com/parse-community/ParseLiveQuery-iOS-OSX/pull/188

@mrmarcsmith - fyi.

**Pull request merged**
