### PR TITLE
Adding back in LiveQueryDemo-ObjC

### PR DESCRIPTION
**Pull request by cbaker6**
- [x] Removed LiveQueryDemo-ObjC run in circle by accident, adding back
- [x] Added watchOS to pod spec
- [x] Remove unnecessary bundle install in circle as it wastes time (leaves caching just in case it’s needed in the future)
- [x] Moved all builds from travis and circle to GitHub Actions (Xcode 12.2), except for Carthage which is Circle (Xcode 11.7)

### CODE REVIEW

**Comment by cbaker6** [comment]
@TomWFox can you replace travis in the branch protections with ci/cocoapods ci/docs? Also, you may need to copy the travis COCOAPODS_TRUNK_TOKEN to Github secrets.

**Comment by cbaker6** [comment]
@TomWFox I switched all tests to actions except for Carthage since it's a resource hog, that one can stay on circle. I'll do the same on the iOS SDK shortly

**Comment by TomWFox** [comment]
I just put a fresh token into GH secrets.

**Comment by cbaker6** [comment]
I updated the badges on here. One "ci" for the actions build on the main branch. The second "release" that shows the status of actions for "release" (pods and docs in the future in this repos case). The release one won't show properly until we try the first release via a tag.

@TomWFox what do you think about this? I've also done the same thing for the iOS SDK. Feel free to adjust if needed.

**Comment by TomWFox** [comment]
Sounds good to me!

**Review by mtrezza — APPROVED** [review]

**Pull request merged**
