### PR TITLE
Updates for bolts 1.9.0

### PR DESCRIPTION
**Pull request by felix-dumit**
Small changes to make this library compatible with the latest `1.9.0` Bolts release.

### CODE REVIEW

**Review by flovilmart — APPROVED** [review]

**Comment by flovilmart** [comment]
We’ll new to bump the Parse SDK as well, working on a release now

**Comment by ijameelkhan** [comment]
this still having issues.

screen shot 2018-01-03 at 4 54 26 pm

**Comment by felix-dumit** [comment]
@flovilmart I updated to `2.3.0` but then I started to get this error on compile:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_BFTaskCompletionSource", referenced from:
      objc-class-ref in BoltsHelpers.o
```

I had to add an explicit dependency to `Bolts` to fix it 422dcc2

**Comment by flovilmart** [comment]
@felix-dummit this is very odd that the dependency to bolts need to be explicit as it should be provided by the Parse SDK itself. But i’ll Have a look. Also we’re almost releasing the 1.7.0 branch for the Parse SDK which contains proper error handling As bolts 1.9 remove support for catching exceptions and was making the SDK crash

**Comment by felix-dumit** [comment]
Ok I was able to fix it. Turns out I had `Parse` and `Parse/FacebookUtils` in my podfile.
Removing it I was able to use `2.3.0`

**Comment by Vortec4800** [comment]
I'm having this exact same problem now, upgrading Parse to 1.17.x and LiveQuery to 2.4.x.

EDIT: Was able to fix this by manually adding Bolts to the list of linked frameworks for the ParseLiveQuery framework in the Pods project. Seems like adding Bolts as a dependency in the Podfile does this automatically, but this PR hasn't been merged yet so it's not happening at the moment.

**Comment by 15458434** [comment]
When is this going to get merged?

**Comment by flovilmart** [comment]
@15458434 you should not need this PR, the latest release 2.4.0 should be fine on it’s own

**Comment by Vortec4800** [comment]
I can confirm the latest 2.4.0 release still has this issue, and this PR is still necessary to tell Cocoapods that it depends on Bolts so it gets linked.

**Pull request merged**
