### PR TITLE
⚡️ Release 2.5.0

### PR DESCRIPTION
**Pull request by maxkattner**
This updates both the Changelog and podspec file to set the version to `2.5.0`.
Please let me know if I overlooked something that needs to be updated as well.

Thanks for your quick feedbacks! :)

### CODE REVIEW

**Comment by flovilmart** [comment]
CAN you update the plist? https://github.com/parse-community/ParseLiveQuery-iOS-OSX/blob/master/Sources/ParseLiveQuery/Info.plist

**Comment by maxkattner** [comment]
Oh, didn’t catch that. Done in 5811624

**Comment by flovilmart** [comment]
Thanks! Let’s see if this goes!

**Review by flovilmart — APPROVED** [review]

**Comment by flovilmart** [comment]
Looks like the publication failed. Did you see the logs on Travis CI?

**Comment by HeEAaD** [comment]
The linting of the Pod failed with
 > - ERROR | xcodebuild:  Starscream/Sources/Starscream/WebSocket.swift:24:8: error: no such module 'CommonCrypto'

I opened PR #179 to do a full `pod lib lint` during development to catch CocoaPods issues early.

**Comment by flovilmart** [comment]
Awesome! I’ll change the tag and attempt another release!

**Comment by flovilmart** [comment]
Well... this didn’t do it 

Validating podspec
 -> ParseLiveQuery (2.5.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Malformed version number string ) during validation.

https://travis-ci.org/parse-community/ParseLiveQuery-iOS-OSX/jobs/484822817

**Comment by HeEAaD** [comment]
I guess it's an issue if of the outdated CocoaPods version 1.4.0 and should be fixed in [1.5.3](https://github.com/CocoaPods/CocoaPods/releases/tag/1.5.3). I opened PR #180 to upgrade to the latest stable CocoaPods release.

**Comment by flovilmart** [comment]
Ah... let’s see how it goes!

**Comment by flovilmart** [comment]
@HeEAaD this is published now, I had to regenerate a cocoapods session somehow.

**Comment by HeEAaD** [comment]
> @HeEAaD this is published now, I had to regenerate a cocoapods session somehow.

Thanks a lot!

**Comment by flovilmart** [comment]
No problem! This should be good to go for the future too

**Pull request merged**
